### ISSUE TITLE
Error in 2.3.3 definition of vector norm equivalence

### ISSUE THREAD

**Issue by li-richard** [OrionQuest/Numacom#1]
Definition reads: Two vector norms ∥x∥_a and ‖x‖b are called equivalent if there exist real numbers c,d>0, such that c*∥x∥_a ≤ ∥x∥_b ≤ ∥x∥_a

Last part of the inequality is incorrect, as it is missing the coefficient d, should read c\*∥x∥_a ≤ ∥x∥_b ≤ d\*∥x∥_a
![14813f1440c101f2a96556c2d9cdd3b6](https://user-images.githubusercontent.com/9093478/32143014-692d6760-bc79-11e7-9e99-284a3c3cc35f.png)

**Comment by OrionQuest** [comment]
Thanks for pointing this out! The notes have been updated.
